# Generated by Django 3.2.7 on 2021-09-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qGen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qGen.customer'),
        ),
    ]
