# Generated by Django 3.2.7 on 2021-09-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qGen', '0003_rename_customer_enduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='no_of_questions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qGen.paragraph')),
            ],
        ),
    ]
