# Generated by Django 3.2.7 on 2021-09-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qGen', '0004_auto_20210927_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.CharField(max_length=2500),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
